var cards = {
	"Core.Start.FanficAuthorTwilight":{url:"START_Fanfic Author Twilight.png"},

	"Core.Pony.AloeAndLotus":{url:"Pony_Aloe & Lotus.png"},
	"Core.Pony.ApplejackBackgroundPony":{url:"Pony_Applejack the Cutest SmartestAll-Around-Best Background Pony.png"},
	"Core.Pony.BBBFFShiningArmor":{url:"Pony_B.B.B.F.F.Shining Armor.png"},
	"Core.Pony.BerryPunch":{url:"Pony_Berry Punch.png"},
	"Core.Pony.BestFoalsitterCadance":{url:"Pony_Best Foalsitter Cadance.png"},
	"Core.Pony.BigMacintosh":{url:"Pony_Big Macintosh.png"},
	"Core.Pony.BlackWidowRarity":{url:"Pony_Black Widow Rarity.png"},
	"Core.Pony.Bloomberg":{url:"Pony_Bloomberg.png"},
	"Core.Pony.BonBon":{url:"Pony_Bon Bon.png"},
	"Core.Pony.Braeburn":{url:"Pony_Braeburn.png"},
	"Core.Pony.BrokenWingRainbowDash":{url:"Pony_Broken-Wing Rainbow Dash.png"},
	"Core.Pony.BulkBiceps":{url:"Pony_Bulk Biceps.png"},
	"Core.Pony.Caramel":{url:"Pony_Caramel.png"},
	"Core.Pony.EarthChangeling":{url:"Pony_Changeling.png"},
	"Core.Pony.UnicornChangeling":{url:"Pony_Changeling_001.png"},
	"Core.Pony.PegasusChangeling":{url:"Pony_Changeling_002.png"},
	"Core.Pony.Cheerilee":{url:"Pony_Cheerilee.png"},
	"Core.Pony.CiderSeasonApplejack":{url:"Pony_Cider Season Applejack.png"},
	"Core.Pony.Crackle":{url:"Pony_Crackle.png"},
	"Core.Pony.CultLeaderFluttershy":{url:"Pony_Cult Leader Fluttershy.png"},
	"Core.Pony.Derpy":{url:"Pony_Derpy.png"},
	"Core.Pony.Discord":{url:"Pony_Discord.png"},
	"Core.Pony.DoctorWhooves":{url:"Pony_Doctor Whooves.png"},
	"Core.Pony.DramaticallyWoundedRarity":{url:"Pony_DramaticallyWounded Rarity.png"},
	"Core.Pony.DruidFluttershy":{url:"Pony_Druid Fluttershy.png"},
	"Core.Pony.Flim&Flam":{url:"Pony_Flim & Flam.png"},
	"Core.Pony.FreedomFighterPinkiePie":{url:"Pony_Freedom Fighter Pinkie Pie.png"},
	"Core.Pony.Gilda":{url:"Pony_Gilda.png"},
	"Core.Pony.GrannySmith":{url:"Pony_Granny Smith.png"},
	"Core.Pony.GypsyWitchPinkiePie":{url:"Pony_Gypsy Witch Pinkie Pie.png"},
	"Core.Pony.HeartlessDictatorRarity":{url:"Pony_Heartless Dictator Rarity.png"},
	"Core.Pony.IronWill":{url:"Pony_Iron Will.png"},
	"Core.Pony.Kefentse":{url:"Pony_Kefentse.png"},
	"Core.Pony.Lyra":{url:"Pony_Lyra.png"},
	"Core.Pony.MahouShoujoDerpy":{url:"Pony_Mahou Shoujo Derpy.png"},
	"Core.Pony.MajorGeneralDash":{url:"Pony_Major General Dash.png"},
	"Core.Pony.MoeFluttershy":{url:"Pony_Moe Fluttershy.png"},
	"Core.Pony.MortalCelestia":{url:"Pony_Mortal Celestia.png"},
	"Core.Pony.MrCake":{url:"Pony_Mr. Cake.png"},
	"Core.Pony.MrsCake":{url:"Pony_Mrs. Cake.png"},
	"Core.Pony.NightmareMoon":{url:"Pony_Nightmare Moon.png"},
	"Core.Pony.Octavia":{url:"Pony_Octavia.png"},
	"Core.Pony.Pinkamena":{url:"Pony_Pinkamena.png"},
	"Core.Pony.PonyJoe":{url:"Pony_Pony Joe.png"},
	"Core.Pony.PrinceBlueblood":{url:"Pony_Prince Blueblood.png"},
	"Core.Pony.PrincessCadance":{url:"Pony_Princess Cadance.png"},
	"Core.Pony.PrincessCelestia":{url:"Pony_Princess Celestia.png"},
	"Core.Pony.PrincessLuna":{url:"Pony_Princess Luna.png"},
	"Core.Pony.PrivateEyeTwilight":{url:"Pony_Private Eye Twilight.png"},
	"Core.Pony.QueenChrysalis":{url:"Pony_Queen Chrysalis.png"},
	"Core.Pony.RoadWarriorSpike":{url:"Pony_Road Warrior Spike.png"},
	"Core.Pony.RoyalGuardHank":{url:"Pony_Royal Guard Hank.png"},
	"Core.Pony.RoyalGuardShiningArmor":{url:"Pony_Royal GuardShining Armor.png"},
	"Core.Pony.SharpshooterApplejack":{url:"Pony_Sharpshooter Applejack.png"},
	"Core.Pony.SmartyPants":{url:"Pony_Smarty Pants.png"},
	"Core.Pony.StarStudentTwilight":{url:"Pony_Star Student Twilight.png"},
	"Core.Pony.StarswirlTheBearded":{url:"Pony_Starswirl the Bearded.png"},
	"Core.Pony.SuperSpyTwilight":{url:"Pony_Super Spy Twilight.png"},
	"Core.Pony.TheGreatAndPowerfulTrixie":{url:"Pony_The Greatand Powerful Trixie.png"},
	"Core.Pony.TheWonderbolts":{url:"Pony_The Wonderbolts.png"},
	"Core.Pony.Tom":{url:"Pony_Tom.png"},
	"Core.Pony.TsundereRainbowDash":{url:"Pony_Tsundere Rainbow Dash.png"},
	"Core.Pony.VinylScratch":{url:"Pony_Vinyl Scratch.png"},
	"Core.Pony.YoungAndHotGrannySmith":{url:"Pony_Young and HotGranny Smith.png"},
	"Core.Pony.Zecora":{url:"Pony_Zecora.png"},

	"Core.Ship.Amnesia": {url:"Ship_Amnesia!.png"},
	"Core.Ship.BadPonyGoToMyRoom": {url:"Ship_Bad Pony! Go to My Room!.png"},
	"Core.Ship.BeachEpisode": {url:"Ship_Beach Episode.png"},
	"Core.Ship.BoredOnASundayAfternoon": {url:"Ship_Bored on aSunday Afternoon.png"},
	"Core.Ship.CabinInTheWoodsAwooo": {url:"Ship_Cabin in theWoods Awooo!.png"},
	"Core.Ship.CanITellYouASecret": {url:"Ship_Can I Tell You a Secret.png"},
	"Core.Ship.CheckingItOffMyList": {url:"Ship_Checking It Off My List.png"},
	"Core.Ship.ClosedDoorNegotiations": {url:"Ship_Closed Door Negotiations.png"},
	"Core.Ship.CrossoverFic": {url:"Ship_Crossover Fic!.png"},
	"Core.Ship.CultMeeting": {url:"Ship_Cult Meeting.png"},
	"Core.Ship.CutieMarkCrusadersMatchmakers": {url:"Ship_Cutie Mark CrusadersMatchmakers!.png"},
	"Core.Ship.Detention": {url:"Ship_Detention.png"},
	"Core.Ship.DivineIntervention": {url:"Ship_Divine Intervention.png"},
	"Core.Ship.DoYouThinkLoveCanBloomEvenOnABattlefield": {url:"Ship_Do You Think Love Can BloomEven on a Battlefield.png"},
	"Core.Ship.DudeLooksLikeaLady": {url:"Ship_Dude Looks Like a Lady.png"},
	"Core.Ship.FillyhoodCrush": {url:"Ship_Fillyhood Crush.png"},
	"Core.Ship.FromanAlternateDimension": {url:"Ship_From an AlternateDimension.png"},
	"Core.Ship.HaveYouMetMyFriend": {url:"Ship_Have You Met My Friend.png"},
	"Core.Ship.HowToPickUpMaresAReferenceGuide": {url:"Ship_How to Pick Up MaresA Reference Guide.png"},
	"Core.Ship.IReadThatInABookOnce": {url:"Ship_I Read That in a Book Once!.png"},
	"Core.Ship.IWishIKnewHowToQuitYou": {url:"Ship_I Wish I KnewHow to Quit You!.png"},
	"Core.Ship.ItWasYouAllAlong": {url:"Ship_It Was You All Along!.png"},
	"Core.Ship.ItsASign": {url:"Ship_It's a Sign.png"},
	"Core.Ship.LeavingOnAPersonalCrusade": {url:"Ship_Leaving on aPersonal Crusade.png"},
	"Core.Ship.LifeThreateningIllness": {url:"Ship_Life-Threatening Illness.png"},
	"Core.Ship.LovePoisonIsNoJoke": {url:"Ship_Love Poison Is No Joke!.png"},
	"Core.Ship.MyLittleShotgunWedding": {url:"Ship_My LittleShotgun Wedding.png"},
	"Core.Ship.NothingInCommonPerfectAnyway": {url:"Ship_Nothing in Common;Perfect Anyway.png"},
	"Core.Ship.NowKiss": {url:"Ship_Now Kiss!.png"},
	"Core.Ship.OnTheLam": {url:"Ship_On the Lam.png"},
	"Core.Ship.OopsWrongSpell": {url:"Ship_Oops! Wrong Spell..png"},
	"Core.Ship.PutARingOnIt": {url:"Ship_Put a Ring on It.png"},
	"Core.Ship.Rule63": {url:"Ship_Rule 63.png"},
	"Core.Ship.SawYouInADream": {url:"Ship_Saw You in a Dream.png"},
	"Core.Ship.ShmoopyBoo": {url:"Ship_Shmoopy Boo!.png"},
	"Core.Ship.SlapSlapKiss": {url:"Ship_Slap-Slap Kiss.png"},
	"Core.Ship.SoThatsWhatThatDoes": {url:"Ship_So THAT'S What That Does!.png"},
	"Core.Ship.StartlingConfession": {url:"Ship_Startling Confession.png"},
	"Core.Ship.StepIntoMyBasement": {url:"Ship_Step into My Basement.png"},
	"Core.Ship.StuckOnABalconyAllNight": {url:"Ship_Stuck on a BalconyAll Night.png"},
	"Core.Ship.SuspiciouslyRomanticRandomPicnic": {url:"Ship_Suspiciously RomanticRandom Picnic.png"},
	"Core.Ship.TheOtherMare": {url:"Ship_The Other Mare.png"},
	"Core.Ship.ThereAreNoBrakesOnTheLoveTrain": {url:"Ship_There Are No Brakeson the Love Train.png"},
	"Core.Ship.TheyFightCrime": {url:"Ship_They Fight Crime.png"},
	"Core.Ship.TheyreAtItAgain": {url:"Ship_They're at It Again!.png"},
	"Core.Ship.TimeForAnExperiment": {url:"Ship_Time For an Experiment!.png"},
	"Core.Ship.TradingUp": {url:"Ship_Trading Up.png"},
	"Core.Ship.TrappedInAStorm": {url:"Ship_Trapped in a Storm.png"},
	"Core.Ship.UnexpectedPregnancy": {url:"Ship_Unexpected Pregnancy.png"},
	"Core.Ship.WantItNeedIt": {url:"Ship_Want It. Need It..png"},
	"Core.Ship.WeveGottoStopMeetingLikeThis": {url:"Ship_We've Got toStop Meeting Like This.png"},
	"Core.Ship.WhatDidIDoLastNight": {url:"Ship_What Did I Do Last Night!.png"},
	"Core.Ship.WorldwideThreatOfDestruction": {url:"Ship_Worldwide Threat ofDestruction.png"},
	"Core.Ship.YerAPrincessHarry": {url:"Ship_Yer a Princess Harry!.png"},
	"Core.Ship.YouHadMeAtNeigh": {url:"Ship_You Had Me at Neigh.png"},

	"Core.Goal.BuddingCuriosity":{url:"Goal_Budding Curiosity.png"},
	"Core.Goal.CargoShip":{url:"Goal_Cargo Ship.png"},
	"Core.Goal.ChancellorPuddingheadsEntourage":{url:"Goal_Chancellor Puddinghead'sEntourage.png"},
	"Core.Goal.CharityAuction":{url:"Goal_Charity Auction.png"},
	"Core.Goal.CommanderHurricanesArmy":{url:"Goal_Commander Hurricane'sArmy.png"},
	"Core.Goal.DeepCover":{url:"Goal_Deep Cover.png"},
	"Core.Goal.Epidemic":{url:"Goal_Epidemic.png"},
	"Core.Goal.Fabulosity":{url:"Goal_Fabulosity.png"},
	"Core.Goal.FriendshipIsBenefits":{url:"Goal_Friendship is Benefits.png"},
	"Core.Goal.GoForthAndMultiply":{url:"Goal_Go Forth and Multiply.png"},
	"Core.Goal.GoodEnough":{url:"Goal_Good Enough.png"},
	"Core.Goal.HehPeasants":{url:"Goal_Heh. Peasants..png"},
	"Core.Goal.HelpImTrappedInAShippingCardGame":{url:"Goal_Help! I'm Trapped in aShipping Card Game!.png"},
	"Core.Goal.HoldOnINeedToMakeAFlowChart":{url:"Goal_Hold On; I Need toMake a Flow Chart.png"},
	"Core.Goal.HostileTakeover":{url:"Goal_Hostile Takeover.png"},
	"Core.Goal.HotForTeacher":{url:"Goal_Hot for Teacher.png"},
	"Core.Goal.IGuessYoullDo":{url:"Goal_I Guess You'll Do.png"},
	"Core.Goal.ISwearImNotGay":{url:"Goal_I Swear I'm Not Gay!.png"},
	"Core.Goal.InvasiveSpecies":{url:"Goal_Invasive Species.png"},
	"Core.Goal.ItsMagicalHornsAreTouching":{url:"Goal_It's MagicalHorns Are Touching.png"},
	"Core.Goal.ItsNotCreepy":{url:"Goal_It's Not Creepy!.png"},
	"Core.Goal.ItsNotEvil":{url:"Goal_It's Not Evil!.png"},
	"Core.Goal.ItsNotExactlyCheating":{url:"Goal_It's NotEXACTLY Cheating....png"},
	"Core.Goal.JustExperimenting":{url:"Goal_Just Experimenting.png"},
	"Core.Goal.MyFirstSlash":{url:"Goal_My First Slash.png"},
	"Core.Goal.NeedsMoreLesbians":{url:"Goal_Needs More Lesbians.png"},
	"Core.Goal.Paradox":{url:"Goal_Paradox.png"},
	"Core.Goal.Pomf":{url:"Goal_Pomf!.png"},
	"Core.Goal.PrettyPrettyPrincess":{url:"Goal_Pretty Pretty Princess.png"},
	"Core.Goal.PrincessPile":{url:"Goal_Princess Pile.png"},
	"Core.Goal.QueenPlatinum'sCourt":{url:"Goal_Queen Platinum's Court.png"},
	"Core.Goal.Quite":{url:"Goal_Quite..png"},
	"Core.Goal.RainbowDashFanClub":{url:"Goal_Rainbow Dash Fan Club.png"},
	"Core.Goal.Rodeo":{url:"Goal_Rodeo.png"},
	"Core.Goal.Sadfic":{url:"Goal_Sadfic.png"},
	"Core.Goal.SelfInsertion":{url:"Goal_Self-Insertion.png"},
	"Core.Goal.ShiningArmorApprovesofThisExperiment":{url:"Goal_Shining Armor Approvesof This Experiment!.png"},
	"Core.Goal.Shipwrecker":{url:"Goal_Shipwrecker.png"},
	"Core.Goal.TheQuietGame":{url:"Goal_The Quiet Game.png"},
	"Core.Goal.TimeTravelersAmongUs":{url:"Goal_Time Travelers Among Us.png"},
	"Core.Goal.WellMaybe":{url:"Goal_Well...Maybe.png"},
}

export default cards;